# Generated by Django 5.2.16 on 2026-08-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Set automatically from the Role field. Role Admin grants access; Staff and Biomedical Engineer do not.",
                verbose_name="Can open the admin site (administrators only)",
            ),
        ),
    ]
