# Generated by Django 5.2.16 on 2026-08-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipment_name', models.CharField(help_text='The device this accessory is for.', max_length=200)),
                ('stock_qty', models.PositiveIntegerField(default=0, help_text='New backup units in the in-house store.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'equipment_name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'equipment_name'), name='unique_accessory_type_per_equipment')],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('working', 'Working'), ('faulty', 'Faulty'), ('condemned', 'Condemned')], default='working', max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Many accessories are not serialized.', max_length=100)),
                ('condemned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='equipment.equipment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='equipment.accessorytype')),
            ],
            options={
                'verbose_name_plural': 'accessories',
                'ordering': ['type__name', 'id'],
            },
        ),
    ]
