# Generated by Django 5.2.16 on 2026-08-03 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_accessorytype_accessory'),
        ('maintenance', '0003_ppmschedule_ppmrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('replaced', 'Replaced'), ('repaired', 'Repaired')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='equipment.accessorytype')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_events', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_events', to='equipment.equipment')),
                ('new_accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_as_new', to='equipment.accessory')),
                ('old_accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_as_old', to='equipment.accessory')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_events', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
