# Generated by Django 5.2.16 on 2026-08-03 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_manufacturer_and_more'),
        ('maintenance', '0002_complaint_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPMSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Every 6 months'), ('annual', 'Annual')], max_length=20)),
                ('next_due', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ppm_schedule', to='equipment.equipment')),
            ],
            options={
                'ordering': ['next_due'],
            },
        ),
        migrations.CreateModel(
            name='PPMRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text="Snapshot of the schedule's next_due when this PPM was recorded.")),
                ('performed_at', models.DateField()),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('passed_with_remarks', 'Passed with remarks'), ('failed', 'Failed')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineers', models.ManyToManyField(blank=True, related_name='ppm_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppm_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ppm_records', to='maintenance.workorder')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='maintenance.ppmschedule')),
            ],
            options={
                'ordering': ['-performed_at', '-created_at'],
            },
        ),
    ]
