# Generated by Django 5.2.16 on 2026-08-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0003_ppmschedule_ppmrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaultCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable internal code. Set once when the category is created.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Shown to the engineer on the repair completion form.",
                        max_length=200,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Lower numbers appear first in the dropdown.",
                    ),
                ),
            ],
            options={
                "verbose_name": "fault category",
                "verbose_name_plural": "fault categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="workorder",
            name="fault_category",
            field=models.CharField(
                blank=True,
                help_text="Required when completing a repair.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="fault_category_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Required when completing a repair.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workorders",
                to="maintenance.faultcategory",
            ),
        ),
    ]
