# Generated by Django 5.2.16 on 2026-08-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_seed_and_map_fault_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='fault_category',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='fault_category_new',
            new_name='fault_category',
        ),
    ]
