# Generated by Django 5.2.16 on 2026-08-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0006_drop_old_fault_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faultcategory",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Stable internal code. Set once when the category is created.",
                max_length=40,
                unique=True,
            ),
        ),
    ]
