# Generated by Django 5.2.16 on 2026-08-05 15:43

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_assistantmessage_servicemanual_manualchunk_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='manualchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
        migrations.AddField(
            model_name='servicemanual',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='manualchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='ai_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
